language: objective-c
cache: cocoapods
matrix:
  include:
  - osx_image: xcode9
    env: SDK="iphonesimulator10.3" DESTINATION="name=iPhone 6s,OS=9.0"
#  - osx_image: xcode8.3
#    env: SDK="iphonesimulator10.3" DESTINATION="name=iPhone 6s,OS=10.3.1"
env:
  global:
  - WORKSPACE=wallabag.xcworkspace
  - SCHEME=wallabag
before_install:
  - gem install -N cocoapods -v 1.2.0
  - pod repo update > /dev/null
  - gem update fastlane --no-ri --no-rdoc --no-document
  - git clone https://github.com/wallabag/WallabagKit ..
  - cd ../WallabagKit/ && git checkout dev-2.0
  - cd ../wallabag
script:
  - fastlane test
